logFilters:
  - code: YN0001
    level: error
  - code: YN0002
    level: discard
  - code: YN0003
    level: error
  - code: YN0004
    level: error
  - code: YN0005
    level: discard
  - code: YN0006
    level: discard
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
  - code: YN0009
    level: error
  - code: YN0013
    level: discard
  - code: YN0019
    level: discard
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
